### ISSUE TITLE
Equipment Organized Crime 

### ISSUE THREAD

**Issue by elric81** [DaveSpringer/bmg-rap-sheets#21]
Some issues with the equipment, as not being able to select and assign the loyalty tattoo or Old School Training to Boris.

**Comment by DaveSpringer** [comment]
Pushed to production and validated the fix on Boris+Loyalty Tattoo and the SWAT Special Training in Law Forces. Closing issue.

**Comment by elric81** [comment]
Great! Thanks for the app, good job!
